Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicita um valor e exibe seu antecessor
// Autor(a)    : Luiz Miguel
// Data atual  : 02/09/2024
Var
// Seção de Declarações das variáveis 
numero,resultado : inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um numero: ")
leia(numero)
resultado<- numero-1
escreval("O antecessor de",numero," é", resultado)

Fimalgoritmo